import express, {Express, Request, Response, Router} from 'express';
import http from 'http'; 
import {Server} from 'socket.io'; 
import cors from 'cors'; 
import dotenv from 'dotenv';
import {openAPIDocJSONObj} from './library/openAPIDoc';
import swaggerUi from 'swagger-ui-express';
import * as OpenApiValidator from 'express-openapi-validator';
import fs from 'fs'; 
import {
    displayRequestsMiddleware,
    customErrorHandlerMiddleware
} from './middleware';
import {userRouter} from './routes';
import { AjvOptions } from 'express-openapi-validator/dist/framework/ajv/options';


dotenv.config(); 

//write openAPISpec.json from object generated by js-doc to file 
//to be consumed by open-api-validator
fs.writeFile('openApiSpec.json', JSON.stringify(openAPIDocJSONObj), (err) =>{
    if (err) throw err;
    console.log("successfully wrote openAPISpec json file");
})


// create express app
const app:Express = express(); 


//main app middleware
app.use([
    cors({origin: "*"}),
    displayRequestsMiddleware,
    express.json(),
]);

app.use(express.text());
app.use(express.urlencoded({extended: false})); 


//validator middleware

app.use(
	OpenApiValidator.middleware({
		apiSpec: './openApiSpec.json',
		validateRequests: true, 
		validateResponses: true,
        ignorePaths: /.*\/api-docs\/.*/
	})
);

//basic test route 
app.get('/', (req:Request, res:Response) => {
	res.status(200).json({'msg:': 'the rootest path. express + typescript server! woohoo!'}); 
});

//users routes
app.use('/api/users', [express.json(), userRouter]); 

//openAPI documentation routes
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(openAPIDocJSONObj));


// custom error handling middleware 
app.use(customErrorHandlerMiddleware);


//socket server
let receiptArray = [
    {
        itemName: "nachos",
        price: 12.99,
        username: "",
    },
    {
        itemName: "kale salad",
        price: 11.75,
        username: "",
    },
    {
        itemName: "beer",
        price: 7.00,
        username: "",
    },
    {
        itemName: "beer",
        price: 7.00,
        username: "",
    },
    {
        itemName: "carrot cake slice",
        price: 6.00,
        username: "",
    }
];

//create http server
const server = http.createServer(app); 


//create socket.io server
// TODO: add cors to whitelist only local 
const io = new Server(server, {
	cors: {origin: "*"}
}); 

// add socket handlers for BE 
io.on('connection', (socket) => {
	console.log('a user connected'); 
	io.emit('receiptArray', receiptArray); 
	
	socket.on('updateItemUser', (indexNewUsername) =>{
		const {index, newUsername} = indexNewUsername;
		console.log(`receipted updateItemUser event: index: ${index}, newUsername: ${newUsername}`);
		
		receiptArray[index]['username'] = newUsername; 
		io.emit('receiptArray', receiptArray); 
	});
});

//start the http server 
server.listen(process.env.EXPRESS_PORT as string, ()=>{
	console.log(`express running on ts-node listening on port: ${process.env.EXPRESS_PORT}`);
}); 

