openapi: 3.0.3
info:
  title: receiptAppTS API
  version: "1.0"
apis:
  - ../controllers/*.ts
paths:
  /users:
    post:
      summary: creates and persists new User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: successful creation of User
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: integer
                    format: int64
                    msg:
                      type: string
        "400":
          description: catch-all invalid input response
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
components: {}
tags: []
